s = set()
s.add(1)
s.add(10)
s.remove(10)
print(s)
# s1 = {4, 6}
# print(s.isdisjoint(s1))
# print(len(s))
# print(max(s))
# print(min(s))
# s1 = s.union({1, 2, 3})
# s1 = s.intersection({1, 2, 3})
# print(s, s1)
# print(type(s))
# l = [1, 2, 3, 4]
# s_from_list = set(l)
# print(s_from_list)
# print(type(s_from_list))